<template>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-center">{{ modal_header }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body terms-content">
         <p>Welcome to the <strong>Precision Technology Partners Corp. Aka PTP Corp. Portal. Precisiontechpartners.com Internet site</strong> (the "Site", "Service"). These Terms of Service together with PTP Corp.’s Privacy Statement (collectively the "Terms") govern your use of this Site. PTP Corp. may change the Terms of Service from time to time. Your access to the site in any way is evidence of your acceptance of the Terms and the enforcement of said Terms. If you do not agree to these terms and conditions, you may not use the Site. PTP Corp. reserves the right, in its sole discretion, to change, modify, or otherwise alter these Terms at any time effective upon posting of the modified Terms on the Site. Please review the Terms periodically. Your continued use of the Site or any materials or services accessible through it, after such posting or notification means you accept the modifications. The use by you of any content or services accessible through the Site may be subject to your acceptance of separate agreements with PTP Corp. or third parties.</p>

        <p><strong>License and Site Access.</strong> PTP Corp. grants you a limited license to access and make use of the Site. You may not download, or modify any portion of it, except with the express written or e-mailed consent of PTP Corp. The license to use the Site does not include any resale or commercial use of the Site or its contents; or any derivative use of this Site or its contents; or any use of data mining, robots or similar data gathering and extraction tools or processes. You agree not to store in any form, distribute, transmit, display, reproduce, modify, create derivative works from, sell or otherwise exploit any of the content on this site for any purpose. By using the Site, you warrant to PTP Corp. that you will not use the Site, or any of the content obtained from the Site, for any purpose that is unlawful or prohibited by these Terms. PTP Corp. does not grant any license or other authorization to any user of its trademarks, registered trademarks, service marks, or other copyrightable material or other intellectual property, by placing them on this Website. If you violate any of these Terms, your permission to use the Site automatically terminates. In consideration of your use of the Site, you agree to: (a) provide true, accurate, current and complete information about yourself as prompted by the sign-up form, if applicable, and (b) to maintain and update this information to keep it true, accurate, current and complete. If any information provided by you is untrue, inaccurate, not current, or incomplete, PTP Corp. has the right to terminate your account and refuse any and all current or future use of the Site. You agree not to resell or transfer the Site or use of or access to the Site.</p>
        <p><strong> Electronic Communications.</strong> When you visit the Site or send e-mails to us, you are communicating with us electronically. You consent to receive communications from us electronically. We will communicate with you by e-mail or by posting notices on this site. You agree that all agreements, notices, disclosures, and other communications that we provide to you electronically satisfy any legal requirement that such communication be in writing. You are responsible for providing, at your expense, any access to the Internet and any required equipment.</p>

        <p><strong>Conduct.</strong> By using the Site you agree that you will not do any of the following: Restrict or inhibit any other user from using the Site; or Post or transmit any unlawful, fraudulent, libelous, defamatory, obscene, pornographic, profane, threatening, abusive, hateful, offensive, or otherwise objectionable information of any kind, including without limitation any transmissions constituting or encouraging conduct that would constitute a criminal offense, give rise to civil liability, or otherwise violate any local, state, national or foreign law, including without limitation the U.S. export control laws and regulations; or Post or transmit any advertisements, solicitations, chain letters, pyramid schemes, investment opportunities or schemes or other unsolicited commercial communication (except as otherwise expressly permitted by PTP Corp.) or engage in spamming or flooding; or Post or transmit any information or software which contains a virus, trojan horse, worm or other harmful component; or Post, publish, transmit, reproduce, distribute or in any way exploit any information, software or other material obtained through the Site for purposes other than as expressly permitted by the provider of such information, software or other material; or Upload, post, publish, transmit, reproduce, or distribute in any way, information, software or other material obtained through the Site which is protected by copyright, or other proprietary right, or derivative works with respect thereto, without obtaining permission of the copyright owner or right holder.</p>

        <p>PTP Corp. has no obligation to monitor the Site. However, you acknowledge and agree that PTP Corp. has the right to monitor the Site electronically from time to time and to disclose any information as necessary or appropriate to satisfy any law, regulation, or other governmental request, to operate the Service properly, or to protect itself or its subscribers. PTP Corp. will not intentionally monitor or disclose any private electronic-mail message unless required by law. PTP Corp. reserves the right to refuse to post or to remove any information or materials, in whole or in part, that, in its sole discretion, are unacceptable, undesirable, inappropriate or in violation of these Terms of Service.</p>
        <p><strong>Feedback.</strong> PTP Corp. may provide you with a mechanism to provide feedback, suggestions, and ideas, if you choose, about its software and services ("Feedback"). You agree that PTP Corp. may, in its sole discretion, use the Feedback you provide to PTP Corp. in any way, including in future modifications of the Site, multimedia works and/or advertising and promotional materials relating thereto. You hereby grant PTP Corp. a perpetual, worldwide, fully transferable, irrevocable, royalty free license to use, reproduce, modify, create derivative works from, distribute and display the Feedback in any manner and for any purpose.</p>
        <p><strong>Third Party Services.</strong> In connection with your use of the Site, you may be made aware of services, products, offers and promotions provided by third parties, and not by PTP Corp. If you decide to use Third Party Services, you are responsible for reviewing and understanding the terms and conditions governing any Third-Party Services. You agree that the third party, and not PTP Corp., is responsible for the performance of the Third-Party Services.</p>
        <p><strong>Third Party Web Sites.</strong> The Site may contain or reference links to Web sites operated by third party ("Third Party Websites"). These links are provided as a convenience only. Such Third-Party Websites are not under the control of PTP Corp. PTP Corp. is not responsible for the content of any Third-Party Website or any link contained in a Third-Party Website. PTP Corp. does not review, approve, monitor, endorse, warrant, or make any representations with respect to Third Party Websites, and the inclusion of any link in the Service is not and does not imply an affiliation, sponsorship, endorsement, approval, investigation, verification or monitoring by PTP Corp. of any information contained in any Third-Party Website. In no event will PTP Corp. be responsible for the information contained in such Third-Party Website or for your use of or inability to use such website. Access to any Third-Party Website is at Licensee's own risk, and Licensee acknowledges and understands that linked Third Party Websites may contain terms and privacy policies that are different from those of PTP Corp. PTP Corp. is not responsible for such provisions, and expressly denies any liability for them.</p>
        <p><strong>Disclaimer of Warranties.</strong> Your use of the Site, including any applets, software, and content contained therein, is entirely at your own risk. THE SERVICE IS PROVIDED "AS IS," AND TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, PTP CORP., ITS AFFILIATES, LICENSORS, THIRD-PARTY CONTENT OR SERVICE PROVIDERS, DISTRIBUTORS, DEALERS, AND SUPPLIERS (COLLECTIVELY "SUPPLIERS") DISCLAIM ALL GUARANTEES AND WARRANTIES, WHETHER EXPRESS, IMPLIED, OR STATUTORY REGARDING THE SITE AND RELATED MATERIALS INCLUDING ANY WARRANTY OF FITNESS FOR A PARTICULAR PURPOSE, TITLE, MERCHANTABILITY AND NON-INFRINGEMENT. PTP CORP. DOES NOT WARRANT OR GUARANTEE THE ACCURACY, RELIABILITY, COMPLETENESS, USEFULNESS, NON-INFRINGEMENT OF INTELLECTUAL PROPERTY RIGHTS, OR QUALITY OF ANY CONTENT ON THE SITE, REGARDLESS OF WHO ORIGINATES THAT CONTENT. PTP CORP. DOES NOT WARRANT THAT THE SITE IS SECURE, FREE FROM BUGS, VIRUSES, INTERRUPTION, ERRORS, THEFT OR DESTRUCTION OR THAT THE SITE WILL MEET YOUR REQUIREMENTS. YOU EXPRESSLY UNDERSTAND AND AGREE THAT YOU BEAR ALL RISKS ASSOCIATED WITH USING OR RELYING ON THAT CONTENT. PTP CORP. IS NOT LIABLE OR RESPONSIBLE IN ANY WAY FOR ANY CONTENT POSTED ON OR LINKED FROM THE SITE, INCLUDING, BUT NOT LIMITED TO, ANY ERRORS OR OMISSIONS IN CONTENT, OR FOR ANY LOSSES OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF OR RELIANCE ON ANY CONTENT.</p>
        <p><strong>Limitation of Liability.</strong> THE ENTIRE CUMULATIVE LIABILITY OF PTP CORP. AND ITS SUPPLIERS FOR ALL MATTERS ARISING FROM OR RELATING TO THESE TERMS SHALL BE LIMITED TO THE AMOUNT PAID BY THE CUSTOMER FOR THE RELATED SERVICES OR CONTENT PURCHASED FROM PTP CORP., ITS AUTHORIZED RESELLER OR ITS SERVICE PROVIDERS. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, PTP CORP. AND ITS SUPPLIERS SHALL NOT BE LIABLE FOR ANY INDIRECT, SPECIAL, INCIDENTAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES OR FOR DAMAGES RELATING TO TELECOMMUNICATION FAILURES, LOSS, CORRUPTION, SECURITY OR THEFT OF DATA, VIRUSES, SPYWARE,OR THE LIKE, WHETHER BASED IN CONTRACT, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY OR OTHERWISE, EVEN IF PTP CORP. OR ITS SUPPLIERS HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES AND EVEN IF A REMEDY SET FORTH HEREIN IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE. THE LIMITATIONS OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN PTP CORP. AND YOU. PTP CORP. WOULD NOT BE ABLE TO HAVE PROVIDED THE SERVICE WITHOUT SUCH LIMITATIONS.</p>
        <p><strong>Banking, Billing or Other Online Services.</strong> Access to Online Banking, Online Payment, and any other services available through the Internet and selected PTP Corp. products (the "Online Service") is provided by your financial institution and not PTP Corp. You agree not to hold PTP Corp. liable for any loss or damage of any sort incurred as a result of any such dealings with any services provided by your financial institution. Your access may be limited from time to time, depending on the service provided by your Internet service provider or your financial institution. You may be billed for these Online Services by your financial institution, not PTP Corp., and such financial institution may have its own service agreement which will govern the Online Services it provides. You agree to be responsible for all telephone charges associated with your Internet and online service usage.</p>
        <p><strong>Termination and Amendment.</strong> Your privilege to use or access the Site may be terminated by PTP Corp. immediately and without notice if you fail to comply with any term or condition of the Terms. Upon such termination, you must immediately cease accessing or using the Site and agree not to re-register or otherwise make use of the Site. Furthermore, you acknowledge that PTP Corp. reserves the right to take action -- technical, legal or otherwise -- to block, nullify or deny your ability to access the Site. You understand that PTP Corp. may exercise this right in its sole discretion. PTP Corp. reserves the right, in its sole discretion, at any time and from time to time to change, modify or discontinue, temporarily or permanently, the Site (or any part thereof). PTP Corp. shall not be liable to you or other third party for any such modification, suspension, or discontinuance except as expressly provided herein. You agree to defend, indemnify, and hold PTP Corp. and its affiliates harmless from any and all claims, liabilities, costs and expenses, including reasonable attorneys' fees, arising in any way from your use of the Service or the placement or transmission of any message, information, software or other materials through the Service by you or users of your account or related to any violation of these Terms by you or users of your account.</p>
        <p><strong>Miscellaneous.</strong> Except as expressly set forth in these Terms, these Terms of Service are a complete statement of the agreement between you and PTP Corp., and set forth the entire liability of PTP Corp. and its Suppliers and your exclusive remedy with respect to your access and use of the Site. In the event of a conflict between these Terms of Service and the Privacy Policy, these Terms of Service shall prevail. The Suppliers, agents, distributors, dealers, and employees of PTP Corp. are not authorized to make modifications to the Terms, or to make any additional representations, commitments or warranties binding on PTP Corp. Any waiver of the terms herein by PTP Corp. must be in a writing signed by an authorized officer of PTP Corp. and expressly referencing the applicable provisions of the Terms. If any provision of the Terms is invalid or unenforceable under applicable law, then it shall be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law, and the remaining provisions will continue in full force and effect. The Terms will be governed by California law as applied to agreements entered into and to be performed entirely within California, without regard to its choice of law or conflicts of law principles that would require application of law of a different jurisdiction, and applicable federal law. The parties hereby consent to the exclusive jurisdiction and venue in the state courts in Sacramento County, California or federal court for the Northern District of California. Headings are included for convenience only, and shall not be considered in interpreting these Terms. The Terms do not limit any rights that PTP Corp. may have under trade secret, copyright, patent, or other laws. You agree that regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to use of the Site or the Terms must be filed within one (1) year after such claim or cause of action arose or be forever barred.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Disagree</button>
        <button type="button" class="btn btn-success">Agree</button>
      </div>
    </div>
  </div>
</div>
</template>

<script>
export default {
  name: 'TermsConditionsModal',
  data () {
    return {
      modal_header: 'Terms and Condition of Use'
    }
  },
  methods: {
  }
}
</script>

<style scoped>
.terms-content {
  height: 400px;
  overflow-y: scroll;
}
</style>
